name: Build Desktop Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "GOOGLE_CREDENTIALS_JSON='$env:GOOGLE_CREDENTIALS_JSON'" > .env
        
    - name: Build executable
      run: |
        pyinstaller --name=LogProcessor `
          --onefile `
          --windowed `
          --add-data ".env;." `
          --clean `
          --noconfirm `
          main_window.py
        
    - name: Create distribution ZIP
      run: |
        cd dist
        Compress-Archive -Path LogProcessor.exe, ../.env -DestinationPath LogProcessor-Windows.zip
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: LogProcessor-Windows
        path: dist/LogProcessor-Windows.zip

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "GOOGLE_CREDENTIALS_JSON='$GOOGLE_CREDENTIALS_JSON'" > .env
        
    - name: Build Mac app
      run: |
        pyinstaller --name=LogProcessor \
          --onefile \
          --windowed \
          --add-data ".env:." \
          --clean \
          --noconfirm \
          --target-architecture universal2 \
          main_window.py
        
    - name: Create Mac app bundle
      run: |
        cd dist
        mkdir -p LogProcessor.app/Contents/MacOS
        mkdir -p LogProcessor.app/Contents/Resources
        mv LogProcessor LogProcessor.app/Contents/MacOS/
        cp ../.env LogProcessor.app/Contents/Resources/
        # Create Info.plist
        cat > LogProcessor.app/Contents/Info.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleDisplayName</key>
          <string>LogProcessor</string>
          <key>CFBundleExecutable</key>
          <string>LogProcessor</string>
          <key>CFBundleIdentifier</key>
          <string>com.yourdomain.logprocessor</string>
          <key>CFBundleName</key>
          <string>LogProcessor</string>
          <key>CFBundlePackageType</key>
          <string>APPL</string>
          <key>CFBundleShortVersionString</key>
          <string>1.0.0</string>
          <key>LSMinimumSystemVersion</key>
          <string>10.15</string>
          <key>NSHighResolutionCapable</key>
          <true/>
        </dict>
        </plist>
        EOL
        
    - name: Create DMG
      run: |
        cd dist
        hdiutil create -volname "LogProcessor" -srcfolder LogProcessor.app -ov -format UDZO LogProcessor-Mac.dmg
        
    - name: Upload Mac artifact
      uses: actions/upload-artifact@v4
      with:
        name: LogProcessor-Mac
        path: |
          dist/LogProcessor-Mac.dmg
          dist/LogProcessor.app
